/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 neusa_frois.glb 
Author: SrMonteiro (https://sketchfab.com/crispimrafael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neusa-frois-916185bb2d4c48829591ba95958b9dcd
Title: Neusa Frois
*/

import React, { useState, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useSnapshot } from "valtio";
import { easing } from "maath";
import state from "../../contexts/CanvasContext";
import { useGlobalContext } from "../../contexts/GlobalContext";

function Neusa(props) {
  const snap = useSnapshot(state);

  var texture;
  const metallicTest = useTexture({
    map: "./neusa_frois/basecolor.jpg",
    // displacementMap: './neusa_frois/metallic.jpg',
    normalMap: "./neusa_frois/normal.jpg",
    roughnessMap: "./neusa_frois/roughness.jpg",
    aoMap: "./neusa_frois/ao.jpg",
  });

  const defaultTest = useTexture({
    map: "./neusa_frois/textures/Material_2143567292_baseColor.jpeg",
    normalMap: "./neusa_frois/textures/Material_2143567292_baseColor.jpeg",
    roughnessMap: "./neusa_frois/textures/Material_2143567292_baseColor.jpeg",
    aoMap: "./neusa_frois/textures/Material_2143567292_baseColor.jpeg",
  });

  const floorTest = useTexture({
    map: "./neusa_frois/floor/basecolor.jpg",
    // displacementMap: './neusa_frois/floor/height.png',
    normalMap: "./neusa_frois/floor/normal.jpg",
    roughnessMap: "./neusa_frois/floor/roughness.jpg",
    aoMap: "./neusa_frois/floor/ao.jpg",
  });

  const graniteTest = useTexture({
    map: "./neusa_frois/granite/basecolor.jpg",
    displacementMap: "./neusa_frois/granite/disp.png",
    normalMap: "./neusa_frois/granite/normal.jpg",
    roughnessMap: "./neusa_frois/granite/rough.jpg",
    aoMap: "./neusa_frois/granite/ao.jpg",
  });

  const wood = useTexture({
    map: "./neusa_frois/wood/basecolor.jpg",
    displacementMap: "./neusa_frois/wood/dis.png",
    normalMap: "./neusa_frois/wood/normal.jpg",
    roughnessMap: "./neusa_frois/wood/roughness.jpg",
    aoMap: "./neusa_frois/wood/ao.jpg",
  });

  const aiT = useTexture({
    map: snap.aiTextureURL,
  })

  if (snap.granite) {
    texture = graniteTest;
  } else if (snap.wood) {
    texture = wood;
  } else if (snap.white) {
    texture = floorTest;
  } else if (snap.aiTexture) {
    texture = aiT;
  }

  const stateString = JSON.stringify(snap);

  const { nodes, materials } = useGLTF("./Models/neusa_frois.glb");

  return (
    <group {...props} dispose={null} key={stateString}>
      <group scale={0.025}>
        <group
          position={[93.504, 45.276, -78.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["SlidingDoor001_Material_#2146801343_0"].geometry}
            material={materials.Material_2146801343}
          />
          <mesh
            geometry={nodes["SlidingDoor001_Material_#2146801355_0"].geometry}
            material={materials.Material_2146801355}
          />
        </group>
        <group
          position={[93.504, 64.961, 227.54]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["SlidingWindow002_Material_#2146801343_0"].geometry}
            material={materials.Material_2146801343}
          />
          <mesh
            geometry={nodes["SlidingWindow002_Material_#2146801355_0"].geometry}
            material={materials.Material_2146801355}
          />
        </group>
        <group
          position={[93.504, 64.961, 11.811]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["SlidingWindow003_Material_#2146801343_0"].geometry}
            material={materials.Material_2146801343}
          />
          <mesh
            geometry={nodes["SlidingWindow003_Material_#2146801355_0"].geometry}
            material={materials.Material_2146801355}
          />
        </group>
        <group
          position={[18.701, 64.961, -270.669]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["SlidingWindow004_Material_#2146801343_0"].geometry}
            material={materials.Material_2146801343}
          />
          <mesh
            geometry={nodes["SlidingWindow004_Material_#2146801355_0"].geometry}
            material={materials.Material_2146801355}
          />
        </group>
        <group
          position={[-78.819, 77.107, 83.29]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_011_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.868, 77.107, 74.017]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_012_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-77.621, 77.107, 91.626]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_013_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.281, 77.107, 42.015]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_014_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.34, 77.107, 34.052]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_015_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.702, 77.107, 51.495]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_016_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.22, 62.96, 82.707]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_017_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.207, 62.96, 73.622]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_018_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.102, 62.96, 91.704]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_019_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.281, 62.96, 42.131]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_020_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.223, 62.96, 34.267]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_021_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.799, 62.96, 50.438]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_022_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-77.302, 48.813, 82.272]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_023_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.514, 48.813, 74.062]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_024_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.788, 48.813, 92.125]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_025_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.265, 48.813, 42.405]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_026_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.355, 48.813, 33.594]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_027_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-80.186, 48.813, 51.68]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_028_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.261, 34.667, 82.119]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_029_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-77.426, 34.667, 73.754]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_030_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-77.932, 34.667, 91.198]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_031_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.492, 34.667, 42.565]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_032_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.351, 34.667, 32.67]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_033_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.196, 34.667, 51.537]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_034_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.963, 20.52, 83.157]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_035_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.108, 20.52, 73.598]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_036_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.964, 20.52, 91.296]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_037_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.885, 20.52, 42.733]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_038_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.436, 20.52, 32.886]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_039_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-79.104, 20.52, 50.317]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_040_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.478, 6.914, 80.418]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_041_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.474, 6.914, 72.229]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_042_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-78.279, 6.914, 88.54]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_043_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-81.399, 6.914, 38.621]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_044_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-80.418, 6.914, 30.702]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_045_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <group
          position={[-81.039, 6.914, 47.357]}
          rotation={[-1.571, 0, 2.924]}
          scale={0.068}
        >
          <mesh
            geometry={nodes["5#1_046_Material_#3524_0"].geometry}
            material={materials.Material_3524}
            position={[-67.489, -440.982, -82.128]}
          />
        </group>
        <mesh
          geometry={nodes["Line001_Material_#2143567293_0"].geometry}
          material={materials.Material_2143567293}
          position={[-22.638, 60.039, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Group_051_Material_#64_0"].geometry}
          material={materials.Material_64}
          position={[17.565, 42.36, -260.565]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Obj3d66-707242-3-267__0"].geometry}
          material={materials["Obj3d66-707242-3-267__0"]}
          position={[17.289, 14.978, 255.757]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={
            nodes["Obj3d66-707242-32-41_Mat3d66-707242-13-5970_0"].geometry
          }
          material={materials["Mat3d66-707242-13-5970"]}
          position={[69.084, 33.51, 117.552]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Obj3d66-707242-34-401__0"].geometry}
          material={materials["Obj3d66-707242-3-267__0"]}
          position={[69.056, 52.298, 117.602]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Obj3d66-707242-36-470__0"].geometry}
          material={materials["Obj3d66-707242-3-267__0"]}
          position={[69.068, 45.507, 117.611]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Obj3d66-707242-38-435__0"].geometry}
          material={materials["Obj3d66-707242-3-267__0"]}
          position={[69.068, 58.833, 117.611]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Object280_Material_#2143566212_0"].geometry}
          material={materials.Material_2143566212}
          position={[-22.351, 118.187, 23.535]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["_72_Material_#2143567290_0"].geometry}
          material={materials.Material_2143567290}
          position={[73.896, 35.532, -196.703]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        {/* table */}
        <mesh
          geometry={nodes["Box076_Material_#2143567292_0"].geometry}
          material={materials.Material_2143567292}
          position={[-29.124, 60.039, 53.947]}
          rotation={[-Math.PI / 2, 0, 0]}
          // visible={false}
        >
          <meshStandardMaterial {...texture} />
        </mesh>
        <mesh
          geometry={
            nodes["Obj3d66-707242-43-731_Material_#2143567294_0"].geometry
          }
          material={materials.Material_2143567294}
          position={[-27.286, 58.954, 23.686]}
          rotation={[-Math.PI / 2, 0, 0]}
          // visible={false}
        ></mesh>
        <mesh
          geometry={nodes["Box065_Material_#2143567291_0"].geometry}
          material={materials.Material_2143567291}
          position={[87.636, 60.158, 75.038]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["_313_Material_#2146801357_0"].geometry}
          material={materials.Material_2146801357}
          position={[42.433, 44.347, 266.481]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[1.25, 1, 1.25]}
        />
        <mesh
          geometry={nodes["Box077_Material_#2146801360_0"].geometry}
          material={materials.Material_2146801360}
          position={[-81.693, 0, 61.122]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Object284__0.geometry}
          material={materials["Obj3d66-707242-3-267__0"]}
          position={[-43.701, 0, -60.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Object285_Material_#2146801358_0"].geometry}
          material={materials.Material_2146801358}
          position={[42.433, 44.347, 266.481]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[1.25, 1, 1.25]}
        />
        <mesh
          geometry={nodes["Object286_Material_#2146801359_0"].geometry}
          material={materials.Material_2146801359}
          position={[42.433, 44.347, 266.481]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[1.25, 1, 1.25]}
        />
        <mesh
          geometry={nodes["Box078_Material_#2146801356_0"].geometry}
          material={materials.Material_2146801356}
          position={[-73.014, 1.969, 61.122]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Object287_Material_#2146801361_0"].geometry}
          material={materials.Material_2146801361}
          position={[-27.286, 58.954, 23.686]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

export default Neusa;

useGLTF.preload("./Models/neusa_frois.glb");
